### ISSUE TITLE
Better syntax highlighting?

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#18]
I'm noticing that students, like, really don't understand how to "chunk up" R code into meaningful pieces. I wonder if better syntax highlighting would help. In particular, the only things that currently get a different color in code chunks are string literals and boolean literals, and also in particular, functions don't -- so I don't think students *see* what I mean when I say "the chisq.test function" or whatever.

A couple of thoughts:
- I found that there's an RStudio option you can turn on to highlight R function calls, which maybe we can turn on by default:
https://support.rstudio.com/hc/en-us/community/posts/211643088-syntax-highlighting-for-known-function-names-parameter-names
- When I turned this option on using the default theme, the color wasn't actually different enough for it to be super noticeable (it was a slightly bluer gray, I guess?). Other themes (in Tools -> Global Options... -> Appearance) make a way bigger distinction between regular text and function names, which seems helpful.
- I also wonder if there's an easy way to get RSTudio / notebooks to use a different highlighter that might be able to detect and highlight named function parameters. Here's some I found that seem promising:
https://github.com/yihui/highr
https://github.com/romainfrancois/highlight

**Comment by VectorPosse** [comment]
I won't have time to look into this now, but possible this summer.

**Comment by VectorPosse** [comment]
There's a cost/benefit trade-off here. I've been reluctant to make changes to global settings in RStudio Server. When we install new versions (or especially when we have to re-install things on the server), sometimes these changes revert back to their defaults. Even when maintaining a list of all the settings we want to change, it gets onerous to try to check them all the time to make sure they're still working. I also try to leave the settings alone so that they match what a user might see if they install RStudio on their own machine. While that isn't common in DATA 220 (and in fact we discourage it), I am always thinking ahead to when I get around to publishing this as a book online, so I don't want anything to be too specific to our Westminster setup.

So I'm putting this one on hold for now. I'm willing to re-visit in the future.
