### ISSUE TITLE
Module 13: don't filter

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#25]
Suggest modifying the example in Module 13 so that it doesn't involve the filter command. Yes, we really carefully tell students not to copy-paste the filter command, but lots of people do it anyway, and then run into silly and not-useful errors.

**Comment by rhinopotamus** [comment]
For instance, because the example uses 69 in the success-failure criterion, several students have been confused about whether they should use 103 or 12 when they're checking.

**Comment by VectorPosse** [comment]
This is a good point, but it's a lot of work to change this. (I'd have to rewrite the whole module basically.) I'm also conflicted because after having gone to the trouble of introducing dplyr verbs in Module 5, we hardly ever use them again. (I'd love to use them more, in fact, but it's hard to find spots where it makes sense.)

So what I'll do for now is include specific guidance in the "Your turn" section at spots where this is likely to come up and be an issue. I want to help students, but at some point, they do have to read carefully and follow directions. They do have to think a little more deeply about what they're doing and not just blindly copy and paste code.
