### ISSUE TITLE
Rubrics: have separate criteria for computing and interpreting the p-value

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#27]
I think it'd help students understand the interpretation of the p-value if we separate the computing-the-number part from the writing-the-sentence part. Then they'd be able to see that, oh, I computed the number right, but now I have to say what it means.

**Comment by rhinopotamus** [comment]
Relatedly, separating out "identify Type 1 vs. Type 2" and "interpret contextually" would be nice.

**Comment by rhinopotamus** [comment]
Heck, it may even be nice to have a separate <div class = "answer"> *box* for these on the R modules.

**Comment by VectorPosse** [comment]
I had to decide carefully here because there are like 5 or 6 places I could potentially divide a "multi-part" rubric entry, and as the rubric is quite long already, I don't want things to spiral out of control. So what I decided is to split any rubric entry that contained both a code chunk and a written answer. So p-values got two entries as requested, as did "Compute and report the test statistic" for similar reasons. I left the Type I/II error entry alone as it's just a single text answer block.
