### ISSUE TITLE
QUESTION: should we be more careful about "test statistic" vs "point estimate"?

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#39]
I've been following ISRS (see e.g. the box at the bottom of p. 70) in being careful about the difference between the test statistic and the point estimate: the test statistic, I'm saying to my students, is the recipe we follow, and the point estimate is the number that we get. For instance, in R module 8, I'd say that the test statistic is the difference in proportions, and the point estimate is -0.1532. 

In the R modules, though, this difference is kinda elided. In particular, in the hypothesis testing rubric, we tell students to "report the test statistic" when perhaps we should more carefully be saying "report the point estimate of the test statistic."

Am I making a bigger deal out of this than it really warrants?

**Comment by VectorPosse** [comment]
So I think about these terms differently, and I'm not convinced that the
usage in ISRS supports your view of the test statistic as a "recipe".
Therefore, I don't know that I think the term "point estimate of the test
statistic" makes sense.

Here's why:

A "point estimate" is a number that estimates a population parameter. The
test statistic is not a population parameter, so it can't itself have a
point estimate.

A "statistic" is a number that is a function of data. A "test statistic" is
a statistic that is used in conjunction with a point null hypothesis and a
distributional assumption to compute a P-value.

In the case of a test for one proportion, for example, the point estimate
of p is p-hat. In the process of conducting a hypothesis test, p-hat (the
point estimate) can *also* serve as a test statistic because it can be
compared to p0 using the distributional assumption normal N(p0, sqrt(p0(1 -
p0)/n)) to produce a P-value.

OR, one can compute a z-score. I would not call a z-score a point estimate
because it is not estimating some "true" z-score in the population. (I
guess the notion of a population z-score technically makes some sense, but
that's not how we use it in a hypothesis test because the null value used
to compute the z-score is not the actual true population mean.) But I
*would* call the z-score a test statistic: it's computed from data and it's
used--again with a distributional assumption, this time N(0, 1)--to compute
a P-value.

If you find sources that differ, though, I'd be interested to see other
perspectives on the issue.

**Comment by rhinopotamus** [comment]
Thanks for your detailed reply, which I'm finding really helpful. Let me see if I can tell a better story.

We have some population parameter that we actually care about. Let's say that it's a proportion. There's no way for me to know what its true value really is; the true value is off floating somewhere in platonic space. But I could posit a reasonable (null) hypothesis that it's whatever null value p0.

To test that hypothesis, I can look at some data. Again I can't access any platonic information about the actual real value of p, so I'm going to have to be satisfied by a **point estimate of the true population proportion** p-hat.

I can pretend that my particular p-hat came from me reaching into a sack of all the different possible p-**hats** and pulling one out. A further consequence of my (null) hypothesis is that the sack of all the different possible p-**hats** looks like N(p0, se).

(I think this is where I was thinking incorrectly before: I think I was thinking of the null distribution as the distribution of possible **p**s, not the distribution of possible p-**hats**.)

So then I can be like, well p-hat is probably not exactly the right value of p, but it's probably close, and then I can assess where p-hat is relative to p0 to decide about how likely it is that the true platonic unknowable p is close to p0.

Okay, so maybe another thing we could do is, we could pass to z-scores, because we want to compare two different experiments apples-to-apples. I still have some p0 (which is a guess), I still have some p-hat, but then I pass to z-scores, and now I can look at the z-score that **belongs to** my p-hat -- but I don't want to think of this as z-hat, because there's no true platonic value that z is actually supposed to be! -- and say that all the possible **z**s are distributed like N(0, 1), and assess the plausibility of my null value based on a P-value computed that way.

Is that a more correct story?

What do we do with, like, chi-squared then? Do we think of the observed value of chi-squared as a **point estimate** of anything in particular?

(Also please forgive me using the "issues" tab on your github to educate myself about statistics lol)

**Comment by VectorPosse** [comment]
I think I basically agree with everything you've said now.

> We have some population parameter that we actually care about. Let's say that it's a proportion. There's no way for me to know what its true value really is; the true value is off floating somewhere in platonic space. But I could posit a reasonable (null) hypothesis that it's whatever null value p0.

This is technically a true statement, but is a little misleading in the sense that we don't choose p0 to be our guess for the "true" value of p in a falsificationist model. But that's a philosophical question and not a statistical one.

> Okay, so maybe another thing we could do is, we could pass to z-scores, because we want to compare two different experiments apples-to-apples. I still have some p0 (which is a guess), I still have some p-hat, but then I pass to z-scores, and now I can look at the z-score that belongs to my p-hat -- but I don't want to think of this as z-hat, because there's no true platonic value that z is actually supposed to be! -- and say that all the possible zs are distributed like N(0, 1), and assess the plausibility of my null value based on a P-value computed that way.

Yes. As asymmetric as the notation is, there is a 1-1 correspondence between the set of all possible p-hats in the sampling distribution N(p0, SE(p0)) and the set of possible z-scores in the sampling distribution N(0, 1) under the assumption of the null. (Well, that's not quite true because of the limited range [0, 1] for proportions. It's like some kind of truncated normal distribution I guess.)

> What do we do with, like, chi-squared then? Do we think of the observed value of chi-squared as a point estimate of anything in particular?

Chi-squared is a great example of a test statistic that doesn't correspond to any kind of point estimate. In the case of proportions we could think of something like p-hat as both a point estimate and as a test statistic. Z-scores are test statistics that aren't point estimates, but the close correspondence with p-hats muddles that distinction. There is no issue with chi-square because it doesn't even pretend to estimate any population parameter.

> (Also please forgive me using the "issues" tab on your github to educate myself about statistics lol)

Actually, it's better than a series of emails that only you and I get to share!
