### ISSUE TITLE
out-of-memory error

### ISSUE THREAD

**Issue by Jingsai** [VectorPosse/Intro_Stats#4]
Students cannot generate a html file by clicking Preview for 05_Manipulating_data.Rmd after answering all questions of this r module. RStudio throws an error saying “Error creating notebook pandoc document conversion failed with error 251”. 
 
This should be an out-of-memory error, because, in order to answer all questions in this R module, we have to define about at least 15 large data matrices (usually 22758 *21) and it simply run out of the memory of Westminster RStudio when clicking Preview, even we can run large matrices chuck by chuck in the script.

**Comment by VectorPosse** [comment]
We increased the memory available for Westminster's Rstudio Server accounts. Having said that, I need to find a better way to manage the large data frames in this module.

**Comment by rhinopotamus** [comment]
Okay, it looks like this issue is still an issue, even after the memory increase. Here's two behaviors I've seen today:

- In my session (Chrome, OS X or Chromebook), pandoc gets through about the "arrange" section and then refuses to generate the rest of the notebook. See attachment.
- In a student's session who was just in my office (Safari on OS X), not even the partial file is displayed -- just a blank screen pops up. I can see if I can get the student to export whatever got written to their .nb.html file before pandoc gave up.

I will also note that I don't seem to have any problems creating all the dataframes -- it isn't until pandoc tries to generate the notebook that I start running into memory issues.

**Comment by VectorPosse** [comment]
That is curious. It's not clear why the dataframes can all exist in memory,
and yet the HTML file seems not to render. Weird. Anyway, like I said
before, I'll probably end up restructuring this assignment for next
semester.

**Comment by rhinopotamus** [comment]
Advice on what we should ask students to turn in for this assignment?
