### ISSUE TITLE
Switch R modules 6 and 7?

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/intro_stats#41]
The randomization modules could align a little better with the ISRS textbook if `shuffle` were presented before `rflip`, since the first simulation discussion occurs in the context of the gender discrimination study. 
(In some ways this is not a particularly natural ordering. Maybe the better thing to do long-term is to just ensure that R modules 6 and 7 are independent, so that you could assign them in either order.)

**Comment by VectorPosse** [comment]
Yes, this is one place where I intentionally switched the order. I don't
get why ISRS does the more complicated two proportion test first.

I take your point about making 6 and 7 more independent. I'll look and see
if there are some easy ways to do that.

**Comment by jonasdandrea** [comment]
It may be the more complicated test, but cognitively it is an easier to
compare two groups since the null assumption is that they are "same."
While the single proportion test is "easier" why/how we choose a particular
null value is sometimes arbitrary. Since we are simulating the
distribution and shuffling one of the groups I find it an easier
conversation about setting up hypotheses.

Jonas
$0.02

**Comment by VectorPosse** [comment]
The way I look at it, there are three goals of these simulation modules:

1. Learn about the idea of simulating fake data.
2. Start laying the foundation for hypothesis testing and inferential
thinking.
3. Learn how to do all this in R.

I agree 100% with Jonas that the two-proportion test is somewhat easier for
(2) because of its intuitive null statement. But I'm still convinced that
the one-proportion case is better for (1) and (3). And since there are also
two more modules focused exclusively on (2), the current ordering (counter
to the presentation in ISRS) preferences rflip and the one-proportion
simulation.

**Comment by VectorPosse** [comment]
I think there likely is a way to make these somewhat independent so they can be assigned in either order. But I'm going to postpone that fix to a future round of editing.

**Comment by VectorPosse** [comment]
Rendered moot with new book.
